export const ADD_MESSAGE_RECEIVED = 'ADD_MESSAGE_RECEIVED';
export const REMOVE_MESSAGE_RECEIVED = 'REMOVE_MESSAGE_RECEIVED';
export const ADD_MESSAGE_SENT = 'ADD_MESSAGE_SENT';
export const USERS = 'USERS';
